package com.thetablock.thetaport.enums;

public enum Response {
    SUCCESS,
    WARP_NAME_EXISTS,
    REQUIRE_TWO_POINTS,
    WARP_DOES_NOT_EXIST,
    POINT_ALREADY_LINKED,
    WARP_NOT_LINKED,
    LINK_SYNC_FAILED,
    INVALID_MESSAGE_TYPE,
    WARP_EXISTS,
    PORT_EXCEEDS_LIMIT,
    INVALID_TEMP_WARP, REST_POINTS,
    FIRST_SLOT,
    SECOND_SLOT, ERROR,
    FIRST_POINT_INVALID,
    SECOND_POINT_INVALID,
    INVALID_PORT,
    POINTS_RESET,
    INVALID_LINKED_WARP,
    PAGE_OUT_OF_RANGE,
    DISABLED,
    INVALID_OFFSET,
    WARP_COORDS_IN_USE,
    SUCCESS_INVALID_LINK,
    REQUIRE_CONFIRMED;
}
